/* SPDX-FileCopyrightText: 2026 Florian Lepont
 * SPDX-License-Identifier: Apache-2.0 */
/* The on-device NO CONNECTION hold screen: drawn entirely on-device,
 * with zero server round-trip, on the 2nd consecutive failed wake for a
 * comm/data step. A full pre-rendered frame would cost 960 KB of the
 * 2.4 MB app partition (firmware/partitions.csv) for what is mostly a
 * blank field; Floyd-Steinberg output is aperiodic (each pixel's error
 * depends on every prior pixel) so it cannot be tiled either — the
 * field is computed at draw time from the ~32 KB committed ink mask
 * (fault_screen_mask.h, generated by firmware/tools/gen_fault_screen.py). */
#pragma once

#include <stdbool.h>
#include <stdint.h>

#define FP_FAULT_SCREEN_WIDTH 1200
#define FP_FAULT_SCREEN_HEIGHT 1600
#define FP_FAULT_SCREEN_BYTES (FP_FAULT_SCREEN_WIDTH * FP_FAULT_SCREEN_HEIGHT / 2) /* 960,000 */

/* Sentinel written to FP_NVS_IMAGE_HASH once this screen has been drawn -
 * deliberately never of the "sha256:<64 hex>" shape a real server hash
 * takes (validate.c), so it can never collide with one and so the first
 * healthy poll's hash-skip never mistakes this sentinel for a server
 * picture already on the panel. */
#define FP_FAULT_SCREEN_HASH "fault:no-connection"

/* next_backoff_n is counted AFTER fp_sleep_decide()'s own increment, so
 * 2 means this is the 2nd consecutive failure; a healthy wake resets it
 * to 0. */
#define FP_FAULT_SCREEN_MIN_BACKOFF_N 2

/* Called every FP_FAULT_SCREEN_TICK_ROWS rows during fp_fault_screen_render()
 * so the caller can feed the task watchdog (fp_wake_feed()) - the render
 * itself has no ESP-IDF dependency and cannot call it directly. May be
 * NULL. */
typedef void (*fp_fault_screen_tick_fn)(void);

/* Renders the NO CONNECTION hold screen into `buf`
 * (FP_FAULT_SCREEN_BYTES, PROTOCOL.md §1 packed format: 1600 rows x 600
 * bytes, left pixel of each byte in the high nibble, Black = 0x0,
 * White = 0x1). Fully overwrites every byte - deterministic, so two
 * renders into two differently-pre-filled buffers are byte-identical.
 * `tick` is called (if non-NULL) roughly every 64 rows. */
void fp_fault_screen_render(uint8_t *buf, fp_fault_screen_tick_fn tick);

/* True only when this wake's failed step is one of the allow-listed
 * comm/data tokens (wifi, http, status, json, auth, enrol, secret,
 * config, download, verify — an unlisted token defaults to NOT
 * drawing), the failure counter has reached
 * FP_FAULT_SCREEN_MIN_BACKOFF_N, and the screen has not already been
 * drawn for this outage (`already_shown`, from comparing
 * FP_NVS_IMAGE_HASH against FP_FAULT_SCREEN_HASH). Also excluded:
 * "blit" (the panel path itself just failed), "reset" (the previous
 * wake never reached sleep on its own; retrying risks looping the same
 * fault), "deadline" (the wake budget is already spent), "nvs" (the
 * sentinel can be neither read nor written, so it would redraw every
 * wake). `step` may be NULL, which always returns false. */
bool fp_fault_screen_should_draw(const char *step, uint8_t next_backoff_n, bool already_shown);
