/* SPDX-FileCopyrightText: 2026 Florian Lepont
 * SPDX-License-Identifier: Apache-2.0 */
/* The one on-device dither-and-mask-stamp renderer shared by every hold
 * screen drawn entirely on the device, with zero server round-trip: NO
 * CONNECTION (fault_screen.c) and UPDATING (updating_screen.c). A full
 * pre-rendered frame would cost 960 KB of the 2.4 MB app partition
 * (firmware/partitions.csv) for what is mostly a blank field;
 * Floyd-Steinberg output is aperiodic (each pixel's error depends on
 * every prior pixel) so it cannot be tiled either - the field is
 * computed at draw time from each screen's own small committed ink mask
 * (generated by firmware/tools/gen_fault_screen.py). */
#pragma once

#include <stdbool.h>
#include <stdint.h>

/* One screen's ink mask: a packed 1-bpp bitmap (MSB-first, row stride
 * `stride` bytes) positioned at (x, y) within the full FP_FAULT_SCREEN_
 * WIDTH/HEIGHT canvas (fault_screen.h - the shared full-panel geometry
 * every hold screen renders into). A mask bit of 1 always wins over the
 * dithered field beneath it. */
typedef struct {
    uint16_t x;
    uint16_t y;
    uint16_t w;
    uint16_t h;
    uint16_t stride;
    const uint8_t *bits;
} fp_hold_mask_t;

/* Called every 64 rows during fp_hold_screen_render() so the caller can
 * feed the task watchdog (fp_wake_feed()) - the render itself has no
 * ESP-IDF dependency and cannot call it directly. May be NULL. Same
 * signature as fp_fault_screen_tick_fn (fault_screen.h), by design, so a
 * caller already holding one can pass it straight through. */
typedef void (*fp_hold_screen_tick_fn)(void);

/* Renders `mask` onto a Floyd-Steinberg dithered dark field (target level
 * DITHER_TARGET_LEVEL, hold_screen.c) into `buf`
 * (FP_FAULT_SCREEN_BYTES, PROTOCOL.md §1 packed format: 1600 rows x 600
 * bytes, left pixel of each byte in the high nibble, Black = 0x0,
 * White = 0x1). Fully overwrites every byte - deterministic, so two
 * renders into two differently pre-filled buffers are byte-identical.
 * `tick` is called (if non-NULL) roughly every 64 rows. No-op if `buf` or
 * `mask` is NULL. */
void fp_hold_screen_render(uint8_t *buf, const fp_hold_mask_t *mask, fp_hold_screen_tick_fn tick);
