/* SPDX-FileCopyrightText: 2026 Florian Lepont
 * SPDX-License-Identifier: Apache-2.0 */
/* The on-device UPDATING hold screen: drawn entirely on-device, with zero
 * server round-trip, for the duration of every OTA attempt - including
 * quiet hours and with the display switched off, so the frame always
 * shows it while a firmware update installs. Same technique as the NO
 * CONNECTION screen (fault_screen.h): a committed ink mask
 * (updating_screen_mask.h, generated by
 * firmware/tools/gen_fault_screen.py --screen updating) stamped onto an
 * on-device dithered dark field via the shared hold_screen.c renderer. */
#pragma once

#include <stdint.h>

#include "fault_screen.h" /* FP_FAULT_SCREEN_BYTES - the shared full-panel buffer size every hold screen renders into */
#include "hold_screen.h"

#define FP_UPDATING_SCREEN_BYTES FP_FAULT_SCREEN_BYTES

/* Sentinel written to FP_NVS_IMAGE_HASH once this screen has been drawn -
 * deliberately never of the "sha256:<64 hex>" shape a real server hash
 * takes (validate.c), so it can never collide with one and so the first
 * healthy poll after an OTA attempt always redraws rather than treating
 * this screen as the already-current picture. */
#define FP_UPDATING_SCREEN_HASH "ota:updating"

/* Renders the UPDATING hold screen into `buf` (FP_UPDATING_SCREEN_BYTES,
 * PROTOCOL.md §1 packed format). Fully overwrites every byte -
 * deterministic, so two renders into two differently pre-filled buffers
 * are byte-identical. `tick` is called (if non-NULL) roughly every 64
 * rows. */
void fp_updating_screen_render(uint8_t *buf, fp_hold_screen_tick_fn tick);
